gcs_bucket: "bucket_mrp"
gcs_file: "data/sales_data.csv"
bigquery:
  dataset: "mrp_erp_project"
  table: "erp_table"
  schema:
    - name: "ORDERNUMBER"
      type: "STRING"
      mode: "NULLABLE"
    - name: "QUANTITYORDERED"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "PRICEEACH"
      type: "STRING"
      mode: "NULLABLE"
    - name: "ORDERLINENUMBER"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "SALES"
      type: "STRING"
      mode: "NULLABLE"
    - name: "ORDERDATE"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "STATUS"
      type: "STRING"
      mode: "NULLABLE"
    - name: "QTR_ID"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "MONTH_ID"
      type: "STRING"
      mode: "NULLABLE"
    - name: "YEAR_ID"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "PRODUCTLINE"
      type: "STRING"
      mode: "NULLABLE"
    - name: "MSRP"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "PRODUCTCODE"
      type: "STRING"
      mode: "NULLABLE"
    - name: "CUSTOMERNAME"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "PHONE"
      type: "STRING"
      mode: "NULLABLE"
    - name: "ADDRESSLINE1"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "ADDRESSLINE2"
      type: "STRING"
      mode: "NULLABLE"
    - name: "CITY"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "STATE"
      type: "STRING"
      mode: "NULLABLE"
    - name: "COUNTRY"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "TERRITORY"
      type: "STRING"
      mode: "NULLABLE"
    - name: "CONTACTLASTNAME"
      type: "INTEGER"
      mode: "NULLABLE"
    - name: "CONTACTFIRSTNAME"
      type: "STRING"
      mode: "NULLABLE"
    - name: "DEALSIZE"
      type: "INTEGER"
      mode: "NULLABLE"